# Makefile for comp_seq
# Generated by CMake Version 2.55
#    Build date Mar  4 2016 11:08:00
#    Ryan Koehler, ryan@verdascend.com
# Sun May 29 18:41:08 2016
#

TARGET = comp_seq
CC = gcc
CFLAGS = -Wall -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
SYSLIBS = -lm
OBJS =    autil.o    dfutil.o   mutil.o    putil.o    sutil.o     \
          sysinfo.o  util.o     dna.o      dna_char.o dna_file.o  \
          dna_in.o   dna_loop.o dna_out.o  dna_pair.o dna_pp.o    \
          dna_seqs.o dna_snp.o  snp_char.o comp_seq.o 

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) -o $(TARGET) $(OBJS) ${SYSLIBS}

autil.o:  autil.c    prim.h     

dfutil.o: dfutil.c   prim.h     

mutil.o:  mutil.c    prim.h     

putil.o:  putil.c    prim.h     

sutil.o:  sutil.c    prim.h     

sysinfo.o: sysinfo.c  prim.h     

util.o:   util.c     prim.h     

dna.o:    dna.c      prim.h     dna.h      

dna_char.o: dna_char.c prim.h     dna.h      

dna_file.o: dna_file.c prim.h     dna.h      

dna_in.o: dna_in.c   prim.h     dna.h      

dna_loop.o: dna_loop.c prim.h     dna.h      dna_pair.h 

dna_out.o: dna_out.c  prim.h     dna.h      

dna_pair.o: dna_pair.c prim.h     dna.h      dna_pair.h 

dna_pp.o: dna_pp.c   prim.h     dna.h      dna_pair.h 

dna_seqs.o: dna_seqs.c prim.h     dna.h      

dna_snp.o: dna_snp.c  prim.h     dna.h      

snp_char.o: snp_char.c prim.h     dna.h      

comp_seq.o: comp_seq.c prim.h     dna.h      dna_pair.h comp_seq.h 
