/*
* competfb.h
*
* Copyright 2014 Ryan Koehler, VerdAscend Sciences, ryan@verdascend.com
*
* The programs and source code of the vertools collection are free software.
* They are distributed in the hope that they will be useful,
* WITHOUT ANY WARRANTY OF FITNESS FOR ANY PARTICULAR PURPOSE.  
* 
* Permission is granted for research, educational, and commercial use and 
* modification as long as 1) Code and any derived works are not redistributed
* for any fee, and 2) Proper credit is given to the authors. If you wish to 
* include this software in a product, please contact the authors.
*
*/




/*********************** ppp ********************
* C function listing generated by gen_prot
* Mon Aug 12 12:58:00 2002
*/
/****************************************************************
* competfb.c
*/
int CalcCompEqI(DOUB C0A, DOUB C0B1, DOUB C0B2, DOUB DGAB1T, DOUB DGAB2T,
	DOUB T, DOUB *f1PD, DOUB *f2PD);

