/*
* divinds.h
*
* Copyright 2018 Ryan Koehler, VerdAscend Sciences, ryan@verdascend.com
*
* The programs and source code of the vertools collection are free software.
* They are distributed in the hope that they will be useful,
* WITHOUT ANY WARRANTY OF FITNESS FOR ANY PARTICULAR PURPOSE.  
* 
* Permission is granted for research, educational, and commercial use and 
* modification as long as 1) Code and any derived works are not redistributed
* for any fee, and 2) Proper credit is given to the authors. If you wish to 
* include this software in a product, please contact the authors.
*
*/


/*********************** ppp ********************
* C function listing generated by gen_prot
* Wed Nov 28 08:54:24 2001
*/
/****************************************************************
* divinds.c
*/
double BrillouinIndexD(int nI, int *nAI, int sI);
double BrillouinEvenIndexD(int nI, int *nAI, int sI);
double BrillouinMaxIndexD(int nI, int sI);
double ShannonWeaverIndexD(int nI, int *nAI, int sI);
double ShannonWeMaxIndexD(int sI);
double ShannonWeEvenIndexD(int nI, int *nAI, int sI);
double ShannonWeaver10IndexD(int nI, int *nAI, int sI);
double ShannonWe10MaxIndexD(int sI);
double ShannonWe10EvenIndexD(int nI, int *nAI, int sI);
double SimpsonIndexD(int n, int *nAI, int s);

