# Makefile for tm_util
# Generated by CMakeC Version 2.56
#    Build date Jan 29 2019 21:15:08
#    Ryan Koehler, ryan@verdascend.com
# Fri Feb  1 11:14:58 2019
#

TARGET = tm_util
CC = gcc
CFLAGS = -Wall -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
SYSLIBS = -lm
OBJS =    autil.o    dfutil.o   mutil.o    putil.o    sutil.o     \
          util.o     sysinfo.o  numlist.o  wordlist.o dna.o       \
          dna_char.o dna_file.o dna_in.o   dna_out.o  dna_seqs.o  \
          dna_snp.o  dna_tm.o   snp_char.o table.o    table_io.o  \
          table_str.o table_val.o competfb.o dset.o     dset_tm.o   \
          fbound.o   tm_io.o    tm_pars.o  tm_util.o  

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) -o $(TARGET) $(OBJS) ${SYSLIBS}

autil.o:  autil.c    prim.h     

dfutil.o: dfutil.c   prim.h     

mutil.o:  mutil.c    prim.h     

putil.o:  putil.c    prim.h     

sutil.o:  sutil.c    prim.h     

util.o:   util.c     prim.h     

sysinfo.o: sysinfo.c  prim.h     

numlist.o: numlist.c  prim.h     numlist.h  

wordlist.o: wordlist.c prim.h     wordlist.h 

dna.o:    dna.c      prim.h     dna.h      

dna_char.o: dna_char.c prim.h     dna.h      

dna_file.o: dna_file.c prim.h     dna.h      

dna_in.o: dna_in.c   prim.h     dna.h      

dna_out.o: dna_out.c  prim.h     dna.h      

dna_seqs.o: dna_seqs.c prim.h     dna.h      

dna_snp.o: dna_snp.c  prim.h     dna.h      

dna_tm.o: dna_tm.c   prim.h     dna.h      table.h    tm_pars.h   \
          dset_tm.h  fbound.h   

snp_char.o: snp_char.c prim.h     dna.h      

table.o:  table.c    prim.h     table.h    

table_io.o: table_io.c prim.h     table.h    

table_str.o: table_str.c prim.h     table.h    

table_val.o: table_val.c prim.h     table.h    

competfb.o: competfb.c prim.h     competfb.h 

dset.o:   dset.c     dset.h     prim.h     

dset_tm.o: dset_tm.c  

fbound.o: fbound.c   prim.h     fbound.h   

tm_io.o:  tm_io.c    prim.h     table.h    tm_pars.h  

tm_pars.o: tm_pars.c  prim.h     dna.h      table.h    tm_pars.h   \
          dset_tm.h  

tm_util.o: tm_util.c  prim.h     dna.h      table.h    fbound.h    \
          tm_pars.h  dset_tm.h  competfb.h tm_util.h  
