/*
* wfmerge.h
*
* Copyright 2017 Ryan Koehler, VerdAscend Sciences, ryan@verdascend.com
*
* The programs and source code of the vertools collection are free software.
* They are distributed in the hope that they will be useful,
* WITHOUT ANY WARRANTY OF FITNESS FOR ANY PARTICULAR PURPOSE.  
* 
* Permission is granted for research, educational, and commercial use and 
* modification as long as 1) Code and any derived works are not redistributed
* for any fee, and 2) Proper credit is given to the authors. If you wish to 
* include this software in a product, please contact the authors.
*
*/

#define VERSION_S   "WFMerge, version 0.41"

/*********************** ppp ********************
* C function listing generated by gen_prot
* Mon Sep 25 11:24:21 2000
*/
/****************************************************************
* wfmerge.c
*/
int main(int argc, char **argv);
void WFMergeUse(void);
int WFMergeI(int argc,char **argv);
int SubFrecsI(FREC *fPO,int nw,FREC *sPO);

/***    End of prototype addition ***/
